### ISSUE TITLE
Add --zap flag when uninstalling apps. 

### ISSUE THREAD

**Issue by DeEskalator** [buresdv/Cork#101]
Using brew `rm --zap [Package]` one can uninstall packages and delete all their files (Cache, files in the Library, etc.) thus removing the app entirely from the system. It's an essential reason for me to use brew for managing my casks as deleting the app-package doesn't remove the entirety of an App. 

I'd love if your amazing app would let me specify if I wanted to remove a packages with or without the `--zap`-flag

**Comment by DeEskalator** [comment]
Well I tried it and love it a lot. Two things: 
1. Would be really nice if I could hold ⌥ and the button would change to "Completely Uninstall ..." (just some convenience and a macOS thing to do ig)
2. After I uninstall something, the current view should update too. If I uninstall an app, the window stays the same and still givers me the option to uninstall the app even after its already been uninstalled because the interface doesn't automatically update til I manually exit it. Would be nice if it the uninstall button changed to "install" making it clear that the package is gone

**Comment by buresdv** [comment]
Great :) The update including this feature is out now
