### ISSUE TITLE
Clipping of search field?

### ISSUE THREAD

**Issue by sh95014** [buresdv/Cork#105]
The search field ("Installed Packages"):

<img width="237" alt="Screenshot 2023-05-15 at 3 54 53 PM" src="https://github.com/buresdv/Cork/assets/95387068/1fac32d7-beef-4db6-a08e-b051a21e521a">

<img width="247" alt="Screenshot 2023-05-15 at 4 00 46 PM" src="https://github.com/buresdv/Cork/assets/95387068/340609da-491f-41be-9984-baddecb005a1">

seems to be missing the rounded left and right edges of its background.

5e6f78163e8cebdaa83d8c3d822149bec2dc79d8

**Comment by buresdv** [comment]
This has been happening ever since I updated to Ventura 13.2. It seems to be a SwiftUI bug and I already filed feedback for it, but now it's on Apple to fix this

**Comment by buresdv** [comment]
I tested it again in the newest macOS version and, at least for me, the field is no longer clipped. Is it still happening for you?

**Comment by sh95014** [comment]
I can't build the app anymore due to https://github.com/buresdv/Cork/issues/104

**Comment by buresdv** [comment]
Oh, my apologies, could you try building branch `sidebar-fix`? I tried breaking up the sidebar a bit

**Comment by sh95014** [comment]
Just to be sure, I updated to Xcode 14.3.1 (14E300c) on macOS 13.4 (22F66), and now both the main and sidebar-fix branches build correctly, and this issue no longer appears.

**Comment by buresdv** [comment]
Great to hear!
