### ISSUE TITLE
Scrolling sidebar with arrow keys not possible outside visible boundaries

### ISSUE THREAD

**Issue by chryxc** [buresdv/Cork#109]
Hi, I noticed that it is only possible to scroll through the package list sidebar with up- and down arrow keys when the active item is currently visible. When you reach the top/bottom (of the visible part of the list) you need to scroll with the mouse/trackpad and then click or use the keys to activate the next list item, otherwise nothing happens.

Cork Version: 0:11
OS Version: macOS 13.4
Hardware: MacBook Pro 16" M1 Pro

**Comment by buresdv** [comment]
Hey, this is definitely a SwiftUI problem. Would you be open to reporting it to Apple?

**Comment by buresdv** [comment]
Thank you, keep me updated on the progress 😁 

I will close this for now, but please make another comment here if anything changes
