### ISSUE TITLE
Cannot test the app before purchase

### ISSUE THREAD

**Issue by tbrodbeck** [buresdv/Cork#118]
Hi. 

I wanted to try out this app.

Using the [download link](https://github.com/buresdv/Cork/releases/download/Demo/Cork.zip) gives a 404.

And then I tried out compiling it myself, what gave me these errors:
<img width="1512" alt="Screenshot 2023-08-14 at 21 43 59" src="https://github.com/buresdv/Cork/assets/24418160/ee4c859a-b58d-4812-be97-3eb487cd184d">

I am using Xcode 14.3.1 and a free Apple Development Certificate (Apple id).

**Comment by hecaex** [comment]
Set **Team** to `None` and **Signing Certificate** to `Sign to Run Locally`.
![grafik](https://github.com/buresdv/Cork/assets/10577573/c2f98da9-5914-4726-abba-a6afae5a2dfc)

**Comment by buresdv** [comment]
Hey,

thank you for telling me about the link being dead, I currently updated the demo and forgot to fix the link. I'll get on that ASAP.

I will also clarify the instructions.

**Comment by buresdv** [comment]
Fixed implemented
