### ISSUE TITLE
Severe compiling errors in Cork 1.1 using Xcode 14.3.1 abd Ventura 13.5.1

### ISSUE THREAD

**Issue by shines75** [buresdv/Cork#129]
Hi! I'm Matteo Piemontese from Italy. As always, I followed all compiling instructions carefully, (I use Ventura 13.5.1 and Xcode 14.3.1), but this time I've got severe compiling errors, as you can see in the picture below. Why? In all previous versions, there were no problems at all.

<img width="1400" alt="Istantanea 2023-08-20 alle 06 09 17" src="https://github.com/buresdv/Cork/assets/87176050/5c8439e0-ecb3-450a-9dae-e54b6b18c5f1">

**Comment by RWCoding58** [comment]
Same thing in https://github.com/buresdv/Cork/issues/127. We'll have to wait for a fix.

**Comment by buresdv** [comment]
See if #125 fixed this

**Comment by buresdv** [comment]
Since there are no comments, I take it this issue was resolved.
