### ISSUE TITLE
Replace old navigation API

### ISSUE THREAD

**Issue by buresdv** [buresdv/Cork#145]
Cork is still using the `NavigationView` API. It should get replaced by `NavigationSplitView`.

Considerations:
- The `Home` button still has to work
- Optionally hide the `Toggle Sidebar` button from the window itself. It should stay in the menu bar

**Comment by rscorer** [comment]
SwiftUI Beta:

```
NavigationSplitView {
    SidebarView()
        .toolbar(removing: .sidebarToggle)
} detail: {
    StartPage()
        .frame(minWidth: 600, minHeight: 500)
}
```

(I think that will work :)

**Comment by rscorer** [comment]
It works.

however

`'toolbar(removing:)' is only available in macOS 14.0 or newer`

**Comment by buresdv** [comment]
That works, but there's still one part of this issue that needs to be addressed: the old NavigationLinks. Those are still a part of the old API.

**Comment by rscorer** [comment]
Ah, I’ll look at them next …

**Comment by boscojwho** [comment]
Will take a look at this if it isn't already being worked on =)

**Comment by buresdv** [comment]
> Will take a look at this if it isn't already being worked on =)

Amazing, thanks. Just don't overengineer it, keep the implementation as simple as possible. Keep this post in mind 😄 https://mstdn.social/@davidbures/111020189704685496

**Comment by boscojwho** [comment]
See PR #167 =)
