### ISSUE TITLE
Optionally add basic taps if none are found

### ISSUE THREAD

**Issue by buresdv** [buresdv/Cork#151]
Homebrew now doesn't come with any taps explicitly defined out of the box.

There should be a prompt that will ask the user if they want to add them automatically. This should tap these basic taps:
- `homebrew/core`
- `homebrew/cask`

**Comment by udoschmitz** [comment]
Any updates? Because I see the same as MrBananaPants from https://github.com/buresdv/Cork/issues/111

**Comment by buresdv** [comment]
Hey, I apologize for this taking so long. I will develop this feature on the linked branch and will ping you both when it's ready to be tested. It should be later today

**Comment by buresdv** [comment]
@udoschmitz @MrBananaPants could you please send me the output of `brew tap`?

**Comment by buresdv** [comment]
@udoschmitz @MrBananaPants could you try compiling the linked branch (`missing-taps`) to check if it works?

**Comment by udoschmitz** [comment]
> @udoschmitz @MrBananaPants could you please send me the output of `brew tap`?

Empty for me.

**Comment by udoschmitz** [comment]
> @udoschmitz @MrBananaPants could you try compiling the linked branch (`missing-taps`) to check if it works?

Will do now.

**Comment by buresdv** [comment]
> How do I do that in the existing Xcode project?

You can follow this tutorial: https://streamable.com/wpbp7g

**Comment by udoschmitz** [comment]
> > How do I do that in the existing Xcode project?
> 
> You can follow this tutorial: https://streamable.com/wpbp7g

Thanks, Xcode showed 4 issues, but compiled successfully and seems to work so far :)

**Comment by buresdv** [comment]
Great, so it works fine now?

**Comment by udoschmitz** [comment]
> Great, so it works fine now?

Yup 😊

**Comment by buresdv** [comment]
Sweet, I'll merge it and release a hotfix. Keep an eye on https://mstdn.social/@davidbures, I'll post when it's out 😊
