### ISSUE TITLE
Home button doesn't perform action unless selected sidebar row is visible

### ISSUE THREAD

**Issue by boscojwho** [buresdv/Cork#165]
# Bug Report

## Mandatory Information
Clicking "Home" button doesn't go back to home view until selected sidebar row is visible.

**To Reproduce**
1. Select any row in sidebar (easiest if first row, but all rows have same bug).
2. Scroll that selected row out of view.
3. Click on "Home" button.
4. Detail view doesn't go back to home view unless selected sidebar row is scrolled into view.

**Expected Behavior**
- Home button should cause home view to reappear regardless of sidebar state.

**Screenshots**
https://github.com/buresdv/Cork/assets/2549615/df78466d-e4c3-4e52-91c9-8cd59e00cbf0

**System and Cork Information:**
 - macOS version: Sonoma (latest beta)
 - Cork Version: 1.2 (43)
 - Did you compile Cork yourself?: Yes, Xcode 15.0 beta 8 (15A5229m)

# Checklist
- [x] I filled everything out under **Mandatory Information**
- [x] This bug affects the UI and I have included a screenshot

**Comment by boscojwho** [comment]
Possibly somewhat related to #145:
Will take a quick look tomorrow to see why this is happening 👀

**Comment by boscojwho** [comment]
Took a look, probably makes way more sense to migrate to new `NavigationSplitView` instead of fixing this in the old `NavigationView` =)

**Comment by buresdv** [comment]
> Took a look, probably makes way more sense to migrate to new NavigationSplitView instead of fixing this in the old NavigationView =)

Yeah, I agree. I've tried and failed a few times before. If you want to have a crack at it, I would really appreciate it.

**Comment by buresdv** [comment]
Can confirm that this is reprodcible. Also noticed that when the item scrolls back into view, the staus page gets correctly displayed.

**Comment by boscojwho** [comment]
> > Took a look, probably makes way more sense to migrate to new NavigationSplitView instead of fixing this in the old NavigationView =)
> 
> Yeah, I agree. I've tried and failed a few times before. If you want to have a crack at it, I would really appreciate it.

Yea, I'd be down! Probably will have some time this week =)

**Comment by boscojwho** [comment]
This is fixed in PR #167 =)
