### ISSUE TITLE
See which packages were installed manually and which as dependencies

### ISSUE THREAD

**Issue by buresdv** [buresdv/Cork#21]
This could be very useful to quickly scan which packages might be candidates for deletion.

**Comment by buresdv** [comment]
Could be accomplished by checking the key `installed_on_request` from `brew info --json=v2 [package]`. Seems to be `true` for packages installed manually, and `false` for packages installed as dependencies.

**Comment by buresdv** [comment]
Done!

![Image](https://i.imgur.com/k3c8A7s.jpg)

**Comment by occludedpixel** [comment]
But if `brew upgrade foo` is run, Cork will register `foo` as a installed manually even though it was originally just a dependency?

**Comment by buresdv** [comment]
The moment you manually update a dependency, Homebrew starts tracking it as manually installed, since you manually modified it.

**Comment by occludedpixel** [comment]
I see.. was hoping that Cork had a way of tracking intentionally installed packages that would differentiate between the two given the second point of "Things that Cork makes easier" in the README highlights "Knowing which packages you installed intentionally...". 

Would you happen to have any suggestions on how to work around this?

**Comment by buresdv** [comment]
Tracking which packages were installed intentionally is very difficult in Homebrew itself.

Like you saw, modifying a dependency makes it act as if it was installed manually.

The core problem Cork solves is that 'brew leaves' doesn't actually list which packages were installed intentionally - it uses some weird internal fuckery that sometimes leaves packages out. Cork solves it by taking installation info directly from package metadata - this is what is meant by that "know which packages were installed manually" line.

Of course, I could build a custom internal tracker that would keep track of which packages you actually clicked "Install" on, but then we get into the realm of weird edge cases.

I don’t think building a custom tracking solution would be worth the effort, and it would end up being less accurate than the current metadata system.
