### ISSUE TITLE
Debug info in brew maintenance cache cleaning

### ISSUE THREAD

**Issue by Jerry23011** [buresdv/Cork#212]
# Bug Report

## Mandatory Information
**Describe the bug**
Brew maintenance page shows extraneous message for package cleaning.

**To Reproduce**
Run brew maintenance and read the results for package cleaning.

**Expected Behavior**
An info indicating that there is no cache to clean when there is no cache

**Screenshots**
<img width="913" alt="截屏2023-10-23 12 26 44" src="https://github.com/buresdv/Cork/assets/89069957/72bbacc8-9554-46d8-b380-e445041e36cd">

**System and Cork Information:**
 - macOS version: 13.6
 - Cork Version: v1.3
 - Did you compile Cork yourself?: No

## Optional Information

**Additional context**

# Checklist
- [x] I filled everything out under **Mandatory Information**
- [x] This bug affects the UI and I have included a screenshot

**Comment by buresdv** [comment]
Fixed by 6495985e86caf35be9cda37fee6cddd5e764aeae

**Comment by Jerry23011** [comment]
Thank you :)

**Comment by buresdv** [comment]
No, thank YOU for reporting it :ú
