### ISSUE TITLE
zh_Hans: "last year" and "last month" translations

### ISSUE THREAD

**Issue by sh95014** [buresdv/Cork#219]
# Bug Report

## Mandatory Information
**Describe the bug**
In the context of "Get top packages for:", the value "Last year" likely refers to the 12-month period before today (e.g., November 4, 2022 to November 3, 2023) instead of "去年", which is 2022 (January 1, 2022 to December 31, 2022).

Similarly, "上月" technically refers to October 1, 2023 to October 31, 2023.

Translating "Last three months" as "前三月" is probably fine.

For zh_Hant, I used "一個月來", "三個月來", and "一年來", which isn't perfect but may be less ambiguous than "上月" and "去年".

We might also consider rephrasing "Last year" in English to "Past year" for clarity, although the distinction isn't necessarily clear to all readers.

@Jerry23011

**Comment by Jerry23011** [comment]
That's true, thank you so much! 🙏🏻

**Comment by Jerry23011** [comment]
Reminds me of this website: https://applelocalization.com

It provides official translations in Apple's apps and frameworks, including strings like "Past year" or "Past month"
