### ISSUE TITLE
App crashes when updating obsolete formulae

### ISSUE THREAD

**Issue by cweirup** [buresdv/Cork#22]
When I clicked the "Update" button in the Outdated items section of the main screen, the app crashed and sent me back to Xcode. I've attached the output from the Console.

To recreate:
- You will need at least 1 outdated package.
- Build and launch app.
- Click the "Update" button under the outdated package section in Homebrew Status. The issue happens if "Outdated packages" is expanded or not.

The error in the Console is:

```
SwiftUI/EnvironmentObject.swift:82: Fatal error: No ObservableObject of type UpdateProgressTracker found. A View.environmentObject(_:) for UpdateProgressTracker may be missing as an ancestor of this view.
2023-02-26 22:14:22.612178-0500 Cork[8331:11138509] SwiftUI/EnvironmentObject.swift:82: Fatal error: No ObservableObject of type UpdateProgressTracker found. A View.environmentObject(_:) for UpdateProgressTracker may be missing as an ancestor of this view.
```

Based on a bit of playing around, I believe you may need to add the Environment Object to the ContentView in CorkApp:

```
            ContentView()
                .environmentObject(appState)
                .environmentObject(brewData)
                .environmentObject(availableTaps)
                .environmentObject(selectedPackageInfo)
                .environmentObject(updateProgressTracker)
                .onAppear
                {
                    NSWindow.allowsAutomaticWindowTabbing = false
                }

```
I've also included screenshots of the screen I've referenced and what I see in Xcode. Let me know if you need more info.

[Issue - App Crashes Updating Formulae - Console Output.txt](https://github.com/buresdv/Cork/files/10835789/Issue.-.App.Crashes.Updating.Formulae.-.Console.Output.txt)

![Homebrew Status Screen with Outdated Formulae](https://user-images.githubusercontent.com/216012/221465709-7eaf2f9f-6afb-4d95-a6bc-db6940ea3a3c.png)

<img width="1728" alt="Outdated Formulae Crash in Xcode" src="https://user-images.githubusercontent.com/216012/221465739-bc09db61-9a8e-452a-8c97-aeed9dbc4e22.png">

**Comment by buresdv** [comment]
There's still one problem that I will have to fix: when you update the packages, the UI doesn't update. I logged it as a bug.

**Comment by cweirup** [comment]
I've confirmed that the update fixed the crashing problem. Thanks!

**Comment by buresdv** [comment]
Great, I'll close the issue.
