### ISSUE TITLE
Edit repo cloning command in README to automatically open Xcode project

### ISSUE THREAD

**Issue by RWCoding58** [buresdv/Cork#223]
# Feature Suggestion

## Mandatory Information
**Description**
Just thought it would be slightly more effecient to have it so the command to clone Cork in the README also opens the Xcode project.

Currently, it's:
1. Clone this repo using `git clone https://github.com/buresdv/Cork.git && cd Cork && open .`
2. Double-click `Cork.xcodeproj`. Xcode should open the project

But my suggestion is to make it:
1. Clone this repo using `git clone https://github.com/buresdv/Cork.git && cd Cork && open Cork.xcodeproj`. Xcode should open the project

**Type**
Non-UI improvement

## Checklist
- [x] I have filled out everything under **Mandatory Information**

**Comment by buresdv** [comment]
Good idea. Implemented in be376219992da1d2d8a5c00734e69fa194d1c4f3
