### ISSUE TITLE
Hide dock icon if shown in menu bar

### ISSUE THREAD

**Issue by demoklion** [buresdv/Cork#231]
# Feature Suggestion

## Mandatory Information
**Description**
What would you like to see added?

Hide dock icon if shown in menu bar. It's duplicated in this state.

**Type**
Are you suggesting a UI or non-UI improvement?

non-UI I guess? It's mac's UI, not the app's

**Mockups**
If you are suggesting a UI feature, do you have any mockups of how you want you feature to look?

n/a

## Optional Information
**Additional Information**
Anything you'd like to add?

## Checklist
- [x] I have filled out everything under **Mandatory Information**

**Comment by buresdv** [comment]
This is a good idea, thank you 👍

**Comment by buresdv** [comment]
Implemented in ebb614afdb7f23bd90a757699069d8e0ab9e4282

**Comment by demoklion** [comment]
That was fast, nice!

**Comment by Erlendms** [comment]
Hmm, this was working for me previously. But after doing a fresh reinstall of macOS, Cork won't go away from the dock. 😔 
This happens whether it's hidden or visible in the the menu bar (Bartender).

Here are my General Settings:
![CleanShot 2024-10-27 at 14 55 16@2x](https://github.com/user-attachments/assets/fb81760c-5f20-4476-b899-254fc2e062ec)

I've tried turning off and on the Show in Menu Bar – but what I'm looking for is a Show in the Dock option, heh.

**Anyone else having this issue? Any ideas for a fix?** (I've probably done something dumb! ☺️)

**Comment by buresdv** [comment]
Hey, this behavior had to be disabled due to something caused by Apple. See this issue: https://github.com/buresdv/Cork/issues/408

**Comment by Erlendms** [comment]
> Hey, this behavior had to be disabled due to something caused by Apple. See this issue: #408

Ah, I see. Sucks when that happen!

Hope things shake out on their end eventually, so it can be added back. :) Thanks for a cool app anyway!

**Comment by clintandrewhall** [comment]
For anyone else who wants to hide the app from the menu bar:

You can add the following to `info.plist`:

```
<key>LSUIElement</key>
<true/>
```

It's hacky, but for those of us self-compiling, it's nbd.
