### ISSUE TITLE
Cork doesn't see outdated formulae

### ISSUE THREAD

**Issue by valleydali** [buresdv/Cork#237]
# Bug Report

At the moment I have two formulae (from `homebrew-core`) that need to be updated, according to `brew outdated`. For each formula, the detail page in Cork shows an "outdated" badge. However, the Cork home page ("Homebrew status") does not report them as needing to be updated ("Checking for package updates" spins for a while and then disappears). And running the "Update Packages" menu command reports "No updates available. You're all up to date."

**To Reproduce**
What did you do to trigger this bug?
Waited for some formulae to become out-of-date.

**Expected Behavior**
What did you expect to happen?
I expected Cork to report that these formulae need to be updated, and update them.

**System and Cork Information:**
 - macOS version: 14.1.1
 - Cork Version: 1.3.1 ((47)
 - Did you compile Cork yourself?: no

**Comment by buresdv** [comment]
Hey, the outdated package list shows only the outdated packages that you installed intentionally and not dependencies. This is done so that less-experienced users aren't overwhelmed by tons of outdated packages every day.

This might change in the next version where the dependencies might also get shown depending on this setting: https://github.com/buresdv/Cork/issues/239, but I'm not sure if I'll have time to implement this part

**Comment by valleydali** [comment]
Wow. Well that is disappointing.

I seem to have completely misunderstood what Cork is all about. When I saw your website’s pitch: “With Cork, you can say goodbye to the Terminal,” I assumed that meant that Cork could do everything the `brew` command could do. Or, if not absolutely everything, certainly at least the most common tasks.

And for me there is no single thing I do in Homebrew more frequently than `brew upgrade`. If this basic functionality is “not planned“ for Cork, then I guess I just don’t see the point.

I was expecting a graphical front-end for Homebrew, but this, together with issue #230, have shown me that is not the case at all.

I’m sure Cork is a great product for some people, but I’m sorry, it’s just not for me. I wish you luck with the project.

**Comment by buresdv** [comment]
It's not for everyone, but it is for the vast majority of people. The website states that it's intended mainly for normal users. If you use Cork the way it is intended, that is, only using Cork to interface with `brew`, it works as it should.

I'm surprised that you formed a firm opinion against Cork without waiting a month for this specific issue to get fixed, and that a single issue is enough to turn you away from the entire project.

And Cork *does* do everything that Homebrew can. It covers the vast majority of Homebrew's functionality, and it *is* a graphical frontend for Homebrew. However, it is opinionated (and developers tend to think that opiniation is great); when you go against those opinions (like explicitly forcing something that Cork prevents, as is the case in #230; not to mention #230 is a problem with Homebrew and not Cork), it will obviously break.

**Comment by occludedpixel** [comment]
> Hey, the outdated package list shows only the outdated packages that you installed intentionally and not dependencies. This is because I don't want less-experienced users to be overwhelmed by tons of outdated packages every day.
> 
> This might change in the next version where the dependencies might also get shown depending on this setting: #239, but I'm not sure if I'll have time to implement this part

After cork is open for sometime, I have noticed that the list of outdated packages on the home page changes to include dependences that I did not install intentionally. I have to either restart Cork or toggle the setting General > Package filtering for the list to revert back to only showing packages installed intentionally.

Here is my setup info:
macOS version: 14.1.1 (23B81)
Cork version: 1.3.4 (51)
Did you compile Cork yourself?: yes
