### ISSUE TITLE
Compiling without Xcode

### ISSUE THREAD

**Issue by rakleed** [buresdv/Cork#252]
Is it possible to compile the application without Xcode? Since Xcode itself weighs several tens of gigabytes, it takes a long time to download and takes up a lot of space on devices with 256 GB of memory. Also, after work, it leaves large hashes, and it takes a long time to update. Is it possible to compile only using Command Line Tools for Xcode?

**Comment by buresdv** [comment]
Hey, I unfortunately don't think this is possible
