### ISSUE TITLE
Cork shows homebrew/core and homebrew/cask when they're untapped

### ISSUE THREAD

**Issue by advicepyro** [buresdv/Cork#253]
# Bug Report

## Mandatory Information
**Describe the bug**
In the list of taps, homebrew/cask and homebrew/core are listed, when they're not shown when doing `brew tap`.
I can confirm they're untapped as they don't show up when doing `brew doctor`.

When I click on either, Cork crashes.

**Screenshots**
<img width="981" alt="Screen Shot 2023-12-30 at 11 46 50 PM" src="https://github.com/buresdv/Cork/assets/6377466/551c4112-64e1-4ea6-8efb-588971e9dcf1">

**System and Cork Information:**
 - macOS version: 14.2.1
 - Cork Version: 1.3.3.1
 - Did you compile Cork yourself?: yes

# Checklist
- [x] I filled everything out under **Mandatory Information**
- [x] This bug affects the UI and I have included a screenshot

**Comment by buresdv** [comment]
This problem has been reported a few times before, and it's more of a Homebrew problem than a Cork problem (see https://github.com/Homebrew/brew/issues/16255). Luckily, it's been fixed.

I fixed the crashing part here: https://github.com/buresdv/Cork/commit/76da7a7523ba2d03a02fd133b4b48d9aad168355
