### ISSUE TITLE
German localization formal/informal

### ISSUE THREAD

**Issue by mammutserver** [buresdv/Cork#257]
The German translation of Cork uses both formal and informal language. Should the translation address the user formally or informally?

**Comment by buresdv** [comment]
It should follow whatever first-party Apple software uses. I'm not sure which tone they use, since I don't know German, but the general rule is that it should follow the language guidelines for first-party Apple software.

**Comment by mammutserver** [comment]
I wasn't able to find information about that in the Apple Style Guide but they use informal language in iOS and their website if they address the user/customer directly.

**Comment by buresdv** [comment]
I'm sorry for taking a bit to respond, I was busy at work.

We should follow whatever style the Photos or Pages app has.

**Comment by buresdv** [comment]
@mammutserver do you think I can close this issue?
