### ISSUE TITLE
Monterey?

### ISSUE THREAD

**Issue by Fred-IV** [buresdv/Cork#269]
# Feature Suggestion

Can you lower the version of macOS required to Monterey?

## Mandatory Information
**Description**
What would you like to see added?

**Type**
Are you suggesting a UI or non-UI improvement?

**Mockups**
If you are suggesting a UI feature, do you have any mockups of how you want you feature to look?

## Optional Information
**Additional Information**
Anything you'd like to add?

## Checklist
- [ ] I have filled out everything under **Mandatory Information**

**Comment by buresdv** [comment]
I can't, unfortunately. SwiftUI in Monterey doesn't support the required basic components.
