### ISSUE TITLE
Maintenance result alert's width too large

### ISSUE THREAD

**Issue by hubertdej** [buresdv/Cork#270]
# Bug Report

## Mandatory Information
If you have a large number of unupdated packages, the alert that is shown after the maintenance check doesn't wrap text and is therefore too wide. It doesn't fit on the screen.

**To Reproduce**
1. Have a considerable amount of unupdated packages.
2. Brew Maintenance... -> Tick "Purge Homebrew cache" -> Start

**Expected Behavior**
Alert wraps text.

**Screenshots**
![image](https://github.com/buresdv/Cork/assets/34969251/aacffc0b-9c6a-470f-9ac8-08f087f60255)

**System and Cork Information:**
 - macOS version: Sonoma 14.0
 - Cork Version: 1.3.4
 - Did you compile Cork yourself?: yes

# Checklist
- [x] I filled everything out under **Mandatory Information**
- [x] This bug affects the UI and I have included a screenshot

**Comment by rishatl** [comment]
Hey, I'll take it upon myself, make me assignees, pls

**Comment by rishatl** [comment]
@buresdv, check mr👆🏻pls

**Comment by buresdv** [comment]
Fixed by #271

**Comment by rishatl** [comment]
@buresdv Removing `fixedSize` solved this problem

**Comment by buresdv** [comment]
@rishatl that does fix the padding, but now, most of the text is missing:
![Snímek obrazovky 2024-03-11 v 19 02 17](https://github.com/buresdv/Cork/assets/22037369/cc5a755c-5e08-494d-bfe5-3591b439efa2)

Also, you can expand the sheet to a ludicrous size, which looks bad 😅 
![Snímek obrazovky 2024-03-11 v 19 02 22](https://github.com/buresdv/Cork/assets/22037369/98901e0d-549d-4586-8d1f-160ae08dfa35)

I suppose the `fixedSize()` has to be somewhere. Do you have any other idea?

**Comment by rishatl** [comment]
I propose this solution - a limit on the maximum size with the ability to expand only vertically if there is a lot of text.

**Comment by buresdv** [comment]
That is definitely an interesting solution, but it still suffers from the problem of the sheet being expandable to too large of a size:
![Snímek obrazovky 2024-03-13 v 15 51 54](https://github.com/buresdv/Cork/assets/22037369/5b327c73-10ec-41e4-8851-9476b122e1f3)

Ideally, the text that lists all the packages would expand as needed (with some sort of a layout priority), and then the rest of the sheet would be laid out. But frames in SwiftUI are a huge mystery to me, so I don't really know how to do that

**Comment by buresdv** [comment]
Since nobody reported any issues, I merged the fix into main (54c9ee228f1b01110feea95c33ececa4906719cf) and will consider this bug fixed by it
