### ISSUE TITLE
Cork Hangs during Maintenance

### ISSUE THREAD

**Issue by PitBullCH** [buresdv/Cork#273]
# Bug Report

## Mandatory Information
**Describe the bug**
When I selected maintenance - all options - Cork hung after popping up a garbled output, had to be forced quit. This was repeatable.

**To Reproduce**
Select all options for maintenance - run maintenance - this is repeatable.
Seems to be an issue with one of the first three options - if I just select health check, it is fine.

**Expected Behavior**
I expected maintenance to work and then return ready for next inputs.

**Screenshots**
![Screenshot 2024-03-11 at 17 25 36](https://github.com/buresdv/Cork/assets/48617453/e39a26cd-d6c9-4a8f-b3e1-810f8dd17a4c)

**System and Cork Information:**
 - macOS version: Sonoma 14.3.1
 - Cork Version: 0.1
 - Did you compile Cork yourself?: No - downloaded demo from website.

## Optional Information

**Additional context**
N/A

# Checklist
- [x] I filled everything out under **Mandatory Information**
- [x] This bug affects the UI and I have included a screenshot

**Comment by buresdv** [comment]
Thank you again for the report :) This is the same thing as #272. I can confirm that this bug is fixed in the latest version
