### ISSUE TITLE
Implement licensing scheme

### ISSUE THREAD

**Issue by buresdv** [buresdv/Cork#275]
There has to be a licensing scheme, so versions don't leak

# Current Outline
- Use emails to check if the user purchased Cork
   - If yes, give them access to the full app
   - If no, offer the opportunity to try the demo. This will also make the demo the current version, and not the current old-ass version.

# Considerations
- Somehow bypass this licensing scheme if the user compiled Cork themselves

Relevant for @Jerry23011  and @utkinn

**Comment by buresdv** [comment]
Licensing and demo added, still need to figure out a way to bypass it for self-compiled stuff.

**Comment by dsoundmn** [comment]
This is a great plan. I'm excited that you're considering local builds to bypass the license check. I do self-build, so I'm open to helping with tests.

**Comment by buresdv** [comment]
Licensing scheme has been fully implemented, now there needs to be a way for people who self-compile to bypass this system somehow

**Comment by dsoundmn** [comment]
I had one idea... Not sure how viable... Could you check which certificate was used to sign the code and react accordingly?

**Comment by buresdv** [comment]
@dsoundmn thanks for the link, it's some interesting readong. However, I just can't get it to work. No matter which certificate I use (or if I use a certificate at all), it never gets to the `NSApplication.shared.terminate(self)` part of the function, which is what I'd expect it to do if there was a problem with teh certificate.

**Comment by dsoundmn** [comment]
Bummer... I had low hopes, but if I figure it out, I'll let you know.

**Comment by buresdv** [comment]
Thanks, I'd really appreciate it if you figure something out 😊

**Comment by buresdv** [comment]
Implemented in 97718a48db94f0a612fee36d48fa384007579cbd

![Snímek obrazovky 2024-05-13 v 15 40 30](https://github.com/buresdv/Cork/assets/22037369/9ef525ec-992b-4d3a-98c6-da1aa9d67230)

**Comment by adidahiya** [comment]
I still can't get this to work after https://github.com/buresdv/Cork/commit/97718a48db94f0a612fee36d48fa384007579cbd

I just compiled from main (https://github.com/buresdv/Cork/commit/504b4399fe53ed79df4eadcedf694b52aa9a5543) following all the instructions in the README

I get this dialog:

![image](https://github.com/user-attachments/assets/4a0f75b7-e36c-4a7b-921e-c796d0345d9f)

MacOS 14.5

**Comment by ixxexi** [comment]
I also get the message following the guide to compile cork in Xcode.

**Comment by buresdv** [comment]
Can you please create a new bug report for this?

@adidahiya @ixxexi The testing team and I tried to reproduce this a few times, but we still can't. 

The only things we can think of is using `Clean build folder` in Xcode, or running `tuist clean` and then redoing the install instructions.

**Comment by buresdv** [comment]
@space-esquire https://github.com/buresdv/Cork/issues/new/choose
