### ISSUE TITLE
Show installed dependents of installed formulae

### ISSUE THREAD

**Issue by benadamstyles** [buresdv/Cork#28]
<img width="1012" alt="Screenshot 2023-03-08 at 14 08 12" src="https://user-images.githubusercontent.com/4380655/223721160-42e1a68e-49a0-4c72-875f-0e1367c2ad6c.png">

I can see that `fb303` is installed as a dependency – it would be great to know _what_ it's a dependency of, i.e. which installed package(s) I have that depends on `fb303`.

**Comment by buresdv** [comment]
Just for u

![Image](https://i.imgur.com/b7lITAf.jpg)
