### ISSUE TITLE
macOS 14.4 - Unable to export homebrew backup

### ISSUE THREAD

**Issue by DeanAmiridis** [buresdv/Cork#284]
# Bug Report

## Mandatory Information
**Describe the bug**
When navigating to File > Export a backup, I receive the following error after the spinwheel:

"Couldn't write homebrew backup. Try again or restart cork"

**To Reproduce**
Attempt to export a backup of homebrew.

**Expected Behavior**
What did yo uexpect to happen?

**Screenshots**
![Screenshot-2024-03-21212628@2x](https://github.com/buresdv/Cork/assets/3272137/d0e1ac51-a60d-4bf2-a023-26ff3e883212)

**System and Cork Information:**
 - macOS version: 14.4
 - Cork Version: 1.3.4
 - Did you compile Cork yourself?: No

## Optional Information

**Additional context**
I believe this worked in the past as I have a older backup file it seems. I am wondering if something changed with 14.4. I checked to see if maybe cork was disabled on one of the permissions on the system that restricted it from performing this action. Everything else works as expected. It may be something on my end, but I tried a few things and re-attempted with no luck; wanted to report it just in case someone else faces this issue.

# Checklist
- [X] I filled everything out under **Mandatory Information**
- [X] This bug affects the UI and I have included a screenshot

**Comment by buresdv** [comment]
This happens when the error output for exporting the backup is not empty. Can you try doing `brew bundle dump` in the Terminal and post the output?

**Comment by DeanAmiridis** [comment]
I just updated to version 1.3.5 and now the save dialog comes up and I am able to export the backup file. If it happens again I'll run the **brew bundle dump** and let you know. You can close the issue if you'd like.

**Comment by buresdv** [comment]
Alright, great to hear it works now 😊 I’ll close the issue for now and reopen it if you encounter the problem again
