### ISSUE TITLE
Pin commits instead of branches

### ISSUE THREAD

**Issue by mattmassicotte** [buresdv/Cork#294]
# Feature Suggestion

## Mandatory Information
**Description**
It is convenient, but problematic, to pin SPM packages to branches. Branches changes, which mean that builds are not repeatable. Both `DavidFoundation` and `LaunchAtLogin` are currently pointing to `main`.

It's less-convene it, but far safer, to put specific commits in there. This way, you guarantee that you have controlled what going is going into what version, and that updates are intentional instead of a side-effect of building.

**Type**
Non-UI

**Mockups**

## Optional Information
**Additional Information**

## Checklist
- [x] I have filled out everything under **Mandatory Information**

**Comment by buresdv** [comment]
Oh, good eye! I never noticed they were pointing at a branch. Would it be okay to change them to "Up to Next Major Version", or do you think they should really be pointing to a specific commit?

**Comment by mattmassicotte** [comment]
I think Up to Next Major Version is the right choice if there actually is a release that will work. But, if you need something on a branch that hasn't been released, a specific commit is safest.

**Comment by buresdv** [comment]
Thanks for the tip, I'll fix it up

**Comment by buresdv** [comment]
Fixed in 17f00a503288a6f13ece20134e29cf65434dc048
