### ISSUE TITLE
Add a way to go back to the start page

### ISSUE THREAD

**Issue by buresdv** [buresdv/Cork#30]
There's currently no way to get back to the start page after switching to a `PackageDetailView`. It would be great to add it.

Some ideas:
1. Have a button on the top of the sidebar in a `.toolbar`
2. Have a button on the left of the Cork text in the global `.toolbar`
3. Have a button in the Menu Bar

**Comment by buresdv** [comment]
Sure. Please use the branch `navigation-rewrite`. In `Views → Sidebar → Sidebar View.swift`, there's a button in the `.toolbar` with the label `Go to Start Page`. P/lease bind that functionality to this button.

**Comment by avijeetpandey** [comment]
Understood, thanks for assigning , will raise the merge request as soon as possible

**Comment by buresdv** [comment]
Thank you very much, good luck! :)

**Comment by buresdv** [comment]
How's it going?

**Comment by buresdv** [comment]
No worries, I just ran out of things to do, so I was wondering if you're still working on this or if I should assign it to myself 😊 

As with the strings, I will rebase the branch onto `main`, where we have implemented `.strings` files where applicable. Just do a pull before you start working on this.

**Comment by avijeetpandey** [comment]
Got it , thanks will do myself as soon as possible🤩

**Comment by buresdv** [comment]
Implemented by @andreyrd
