### ISSUE TITLE
Application Badge not updating

### ISSUE THREAD

**Issue by maleghast** [buresdv/Cork#309]
# Bug Report

## Mandatory Information
**Describe the bug**
The Application "badge" suggesting that there are outstanding issues / notifications for Cork is not updating properly, that is to say I am up to date, but the Application Badge is still showing "3" 

**To Reproduce**
Update my packages because I saw the Aplication Badge and now it won't go away, even if I quit the application and restart it.

**Expected Behavior**
When I have addressed any outdated packages I expect the Application Badge to disappear, or set itself to an appropriate new number if in the meantime there are packages that have newly fallen out of being current.

**Screenshots**
<img width="933" alt="Screenshot 2024-04-30 at 12 07 41" src="https://github.com/buresdv/Cork/assets/250003/42c27c95-9ff4-4241-a16a-622e7636cab2">
<img width="939" alt="Screenshot 2024-04-30 at 12 08 02" src="https://github.com/buresdv/Cork/assets/250003/64804498-831e-4cca-bf36-de468c74fa8d">
<img width="292" alt="Screenshot 2024-04-30 at 12 09 29" src="https://github.com/buresdv/Cork/assets/250003/5c0f9d8b-11f4-4dcc-9c13-07daebbee926">

**System and Cork Information:**
 - macOS version: Sonoma 14.4.1
 - Cork Version: 1.3.5 (52)
 - Did you compile Cork yourself?: No

## Optional Information

**Additional context**

# Checklist
- [•] I filled everything out under **Mandatory Information**
- [•] This bug affects the UI and I have included a screenshot

**Comment by buresdv** [comment]
Thanks for the report, I sometimes encounter this, too. I'll bet back to you when I have more information 👍

**Comment by buresdv** [comment]
This might be fixed in the most recent version
