### ISSUE TITLE
Cork reports an Error Updating Homebrew when everything is actually fine...

### ISSUE THREAD

**Issue by maleghast** [buresdv/Cork#310]
# Bug Report

## Mandatory Information
**Describe the bug**
When I update my packages I sometimes get an error message saying that an error occurred when updating Homebrew.  This is very off putting the first couple of times it happens and is confusing, because actually it's being triggered by the fact that Homebrew itself was not updated in the upgrade process, i.e. my Homebrew itself is up to date.

**To Reproduce**
Upgrade packages when Homebrew is already up to date

**Expected Behavior**
I would not expect an error message when nothing is actually wrong.  I think that this may well confuse a lot of users, particularly users who are relying on Cork as they are uncomfortable with the command line.

**Screenshots**
<img width="938" alt="Screenshot 2024-04-30 at 12 08 50" src="https://github.com/buresdv/Cork/assets/250003/ca59f082-ad84-47ce-8693-1afa185d18ed">

**System and Cork Information:**
 - macOS version: Sonoma 14.4.1
 - Cork Version: 1.3.5 (52)
 - Did you compile Cork yourself?: No

## Optional Information

**Additional context**

# Checklist
- [•] I filled everything out under **Mandatory Information**
- [•] This bug affects the UI and I have included a screenshot

**Comment by buresdv** [comment]
Already fixed in #301, will be included in the next release
