### ISSUE TITLE
Add support for brew leaves

### ISSUE THREAD

**Issue by laserhybiz** [buresdv/Cork#313]
# Feature Suggestion

## Mandatory Information
**Description**
Add support for brew leaves, this will help me see the packages that I installed on-request and remove the ones that I don't need anymore rather than see *all* packages and not be sure whether it's a dependency of a different package or not (if I understand correctly what leaves are)

**Type**
Not sure

**Mockups**
If you are suggesting a UI feature, do you have any mockups of how you want you feature to look? no

## Optional Information
**Additional Information**
Anything you'd like to add?

## Checklist
- [x] I have filled out everything under **Mandatory Information**

**Comment by buresdv** [comment]
This is already a feature: https://github.com/buresdv/Cork/issues/247
