### ISSUE TITLE
please clarify the "If it isn't already selected, change the Build Scheme to Self-Compiled in Xcode's toolbar. " line in the installation instructions.

### ISSUE THREAD

**Issue by gkrawiec** [buresdv/Cork#336]
the rest of the instructions are super clear and easy to follow. This one instruction
"If it isn't already selected, change the Build Scheme to Self-Compiled in Xcode's toolbar. "
is a bit confusing as there are 2 places where it says  "self compiled" and selecting the bottom one is not enough.
thank you.

**Comment by buresdv** [comment]
Can yo used a screenshot of what you mean?

**Comment by buresdv** [comment]
I just wanted to ask, have you seen the picture for step 7? It shows the correct place:

![image](https://github.com/buresdv/Cork/assets/22037369/a0b9791f-b177-4aff-aa1b-6c79529454ae)

**Comment by gkrawiec** [comment]
yes, but since the other option for "self-compiled" is not hidden in a menu i just assumed it's a different version of the UI.
Your instructions are not wrong. I just make a suggestion that you clarify this step for those of us who do not use xcode.
