### ISSUE TITLE
Could not load packages

### ISSUE THREAD

**Issue by axelemils** [buresdv/Cork#365]
Downloaded the latest version from Github and when I opened Cork I get this error message:
"Could not load packages (The operation couldn't be completed. (Cork.PackageLoadingError error 0.))"

I have done a few fresh installs using AppCleaner but I get the same error.

Wanted to get into Homebrew and learn but though a GUI would make this easier thus leading me to Cork, looks like a cool app with an awesome design!

<img width="1012" alt="Screenshot 2024-07-18 at 09 13 44" src="https://github.com/user-attachments/assets/c51ae143-eb9e-4f71-9eb2-59b2c9ffde19">

**Comment by buresdv** [comment]
Can you please post the output of the Xcode console when you run Cork?

**Comment by buresdv** [comment]
Closed due to inactivity

**Comment by ranvel** [comment]
I'm having this same issue with 1.4.4.2 (Not from xcode build).

**Comment by buresdv** [comment]
@ranvel Can you create a new issue with the latest build?
