### ISSUE TITLE
Couldn't decipher homebrew response - when viewing taps in Cork.app

### ISSUE THREAD

**Issue by stysedo** [buresdv/Cork#367]
Clicking on any of the items in the 'Added taps' section of the Cork.app sidebar results in the message "Couldn't decipher Homebrew response The operation couldn't be completed. (Cork.JSONParsingError error 1.)

 - macOS version: 14.5
 - Cork Version: 1.4.4. (70)
 - Did you compile Cork yourself?: No. We are using the pre-compiled binary from github.com/buresdv/Cork/releases
 - Homebrew 4.3.10 installed via the .pkg from github.com/Homebrew/brew/releases/download/4.3.10/Homebrew-4.3.10.pkg

![Screenshot 2024-07-26 at 8 18 45 PM](https://github.com/user-attachments/assets/55b0c3c0-f7ab-4808-83f6-110397a5cf53)

**Comment by buresdv** [comment]
Can you please do `which brew` in the Terminal? Just to make sure that the executable is in the correct location.

**Comment by buresdv** [comment]
That's interesting indeed. I have Homebrew installed through the Terminal, and it may be that Homebrew is not in the `$PATH`. While this should not affect Cork, it's one point of divergence between our system.

Would it be too much trouble to install Homebrew through the Terminal?

If you'd be up for it, you can uninstall Homebrew using `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"`, and then install it again using `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

**Comment by buresdv** [comment]
> the response from the uninstall command was that no homebrew was found.

In that case, I think you can just run the install command and it won't break anything.

Don't worry, this is fixable 😊

**Comment by buresdv** [comment]
Closed due to inactivity
