### ISSUE TITLE
Install Multiple Packages at once

### ISSUE THREAD

**Issue by ondohotola** [buresdv/Cork#379]
### Suggestion type

The way Cork works

### What is your idea about?

I wanted to install two packages at the same time but can only mark one at at time

### Why should this be added?

Would be more convenient

### Keeping it real

- [X] Adding suggestion idea is realistic

**Comment by buresdv** [comment]
This feature was implemented for a brief period at the very beginning of development, but it had to be taken out due to the huge problems with concurrency and waiting for various dependencies to be installed. So, unfortunately, this won't be implemented.

Thank you for the idea though :)
