### ISSUE TITLE
Maintenance overview displays at incorrect size

### ISSUE THREAD

**Issue by yerbestpal** [buresdv/Cork#38]
After performing all maintenance jobs, an overview presumably displaying the results of the maintenance is shown. However, it is incorrectly sized, cutting out most information	and UI elements. It is impossible to move on from this window using the mouse, and instead hitting enter closes it (I assume there is a close button that is highlighted). 

![47666](https://user-images.githubusercontent.com/15250241/224299745-29188308-79e2-43ef-ad7a-3832f1a61e3d.png)

**Comment by buresdv** [comment]
This is a SwiftUI bug, I quickly patched it in the latest release. Try it out, it should look fine now.

**Comment by yerbestpal** [comment]
It seems like the latest release isn't available via the brew tap. I don't doubt you've pushed an update, just a heads up.

**Comment by buresdv** [comment]
Yeah, Brew is actually *really* slow with delivering updates, it can sometimes take a few hours for Brew to realize there's been an update.

I would recommend doing `brew update` followed by `brew reinstall --cask cork`, which will force it to download the newest version.
