### ISSUE TITLE
Could not load packages 

### ISSUE THREAD

**Issue by ranvel** [buresdv/Cork#380]
### What were you trying to do?

I am trying to load the application. 

### What was the problem?

<img width="968" alt="Screenshot 2024-08-12 at 10 05 46" src="https://github.com/user-attachments/assets/5268b404-58c2-4ed0-ba45-1b3c37fb2cdc">
I get this error. I even tried restarting and reinstalling it. 

### Error logs

```shell
default	10:17:40.045722-0400	Cork	Scheduled event fired at <private>
default	10:17:43.557277-0400	Cork	No new updates found
default	10:17:43.557296-0400	Cork	Will purge temporary update trackers
default	10:19:37.419399-0400	Cork	Cached downloads contents: <private>
error	10:19:37.421339-0400	Cork	Could not get proxy host
error	10:19:37.432277-0400	Cork	Failed while accessing folder: Error Domain=Cork.PackageLoadingError Code=0
error	10:19:37.432425-0400	Cork	Couldn't find homebrew/core in local taps
error	10:19:37.432439-0400	Cork	Couldn't find homebrew/cask in local taps
default	10:19:37.913218-0400	Cork	Will attempt to place package name
```

### App Version

1.4.4.2

### App Acquisition

Bought

### Final checklist

- [ ] This report is about the interface, and I included screenshots of the problem

**Comment by buresdv** [comment]
I'm really sorry, I forgot about this issue due to real life obligations. 

Does the error still appear in this linked version? [Cork.zip](https://github.com/user-attachments/files/16733167/Cork.zip)

**Comment by ranvel** [comment]
No worries! I'm glad you got the real-life obligations sorted. 

I don't know what happened, but I downloaded this on my M3 mbp, and it didn't work (same issue). Then I downloaded it on my Intel mac and it did work. Then I trashed my homebrew root (/opt/homebrew) and reinstalled the hombrew pkg. And then it did work. 

So all is right in the world again.
Thanks!

**Comment by buresdv** [comment]
Great to hear :) These problems are 99,9% caused by broken Homebrew installs
