### ISSUE TITLE
Error on launch: Package Cellar prevented loading

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [buresdv/Cork#381]
### What were you trying to do?

Launch Cork

### What was the problem?

Error modal window displayed, "Package Cellar prevented loading"
![Screenshot 2024-08-12 at 11 30 15 PM](https://github.com/user-attachments/assets/fecf28a7-8db7-4000-bfd8-2d52212c0007)

### Error logs

```shell
default	23:37:24.297574-0400	Cork	Cached downloads contents: <private>
error	23:37:24.305807-0400	Cork	Could not get proxy host
error	23:37:24.356549-0400	Cork	Couldn't find homebrew/core in local taps
error	23:37:24.356576-0400	Cork	Couldn't find homebrew/cask in local taps
error	23:37:24.376780-0400	Cork	Failed to decode install receipt for package <private> with error <private>
error	23:37:24.379101-0400	Cork	Failed to load contents of install receipt for package <private> with error <private>
error	23:37:24.386383-0400	Cork	Failed to decode install receipt for package <private> with error <private>
error	23:37:24.386569-0400	Cork	Failed to load contents of install receipt for package <private> with error <private>
error	23:37:24.549828-0400	Cork	Failed while accessing folder: Error Domain=Cork.PackageLoadingError Code=1
default	23:37:24.703088-0400	Cork	Will attempt to place package name
```

### App Version

1.4.4

### App Acquisition

Bought

### Final checklist

- [X] This report is about the interface, and I included screenshots of the problem

**Comment by 0n0mat0p03ia** [comment]
Clicking on homebrew/core or homebrew/cask in the Cork UI generates an error: "Couldn't decipher Homebrew response"
![Screenshot 2024-08-12 at 11 42 23 PM](https://github.com/user-attachments/assets/74776ab0-cfde-463f-8333-4dfd37fd6d73)

**Comment by buresdv** [comment]
Can you try compiling the current state of the `main` branch, or trying this new executable? There's some fixes for logging and hopefully they work (it won't solve the problem, but will at least give us better logs)
[Cork.zip](https://github.com/user-attachments/files/16602375/Cork.zip)

**Comment by 0n0mat0p03ia** [comment]
Ran the compiled binary, here's the console output (filtering on `s:com.davidbures.cork`):

error	17:32:46.304975-0400	Cork	Could not get proxy host
default	17:32:46.306179-0400	Cork	Cached downloads contents: <private>
error	17:32:46.365994-0400	Cork	Couldn't find homebrew/core in local taps
error	17:32:46.366033-0400	Cork	Couldn't find homebrew/cask in local taps
error	17:32:46.390208-0400	Cork	Failed to decode install receipt for package Cellar with error The data couldn’t be read because it isn’t in the correct format.
error	17:32:46.392894-0400	Cork	Failed to load contents of install receipt for package Cellar with error error.package-loading.could-not-load-Cellar-at-file:///usr/local/Cellar-because-Couldn't read installation info: %@
error	17:32:46.400456-0400	Cork	Failed to decode install receipt for package Cellar with error The data couldn’t be read because it isn’t in the correct format.
error	17:32:46.401231-0400	Cork	Failed to load contents of install receipt for package Cellar with error error.package-loading.could-not-load-Cellar-at-file:///usr/local/Cellar-because-Couldn't read installation info: %@
error	17:32:46.594623-0400	Cork	Failed while accessing folder: Error Domain=Cork.PackageLoadingError Code=1
default	17:32:46.843456-0400	Cork	Will attempt to place package name

**Comment by buresdv** [comment]
Looking at the output, it's REALLY weird. The logs are saying it's trying to load the container folder for Formulae (`Cellar`) as a version of a package, but I see no situation when that would happen.

Can you try running this binary to see if you get any new messages? We're looking for `The last path component of the requested URL is the package container folder itself - perhaps a misconfigured package folder?`. 
[Cork.zip](https://github.com/user-attachments/files/16605780/Cork.zip)

**Comment by 0n0mat0p03ia** [comment]
Console output running the more recently provided binary:

default	21:40:20.243189-0400	Cork	Scheduled event fired at <private>
error	21:40:20.288625-0400	Cork	Could not get proxy host
default	21:40:20.288952-0400	Cork	Cached downloads contents: <private>
error	21:40:20.350940-0400	Cork	Couldn't find homebrew/core in local taps
error	21:40:20.350955-0400	Cork	Couldn't find homebrew/cask in local taps
error	21:40:20.380563-0400	Cork	Failed to decode install receipt for package Cellar with error The data couldn’t be read because it isn’t in the correct format.
error	21:40:20.381033-0400	Cork	Failed to load contents of install receipt for package Cellar with error error.package-loading.could-not-load-Cellar-at-file:///usr/local/Cellar-because-Couldn't read installation info: The data couldn’t be read because it isn’t in the correct format.
error	21:40:20.395231-0400	Cork	Failed to decode install receipt for package Cellar with error The data couldn’t be read because it isn’t in the correct format.
error	21:40:20.395607-0400	Cork	Failed to load contents of install receipt for package Cellar with error error.package-loading.could-not-load-Cellar-at-file:///usr/local/Cellar-because-Couldn't read installation info: The data couldn’t be read because it isn’t in the correct format.
error	21:40:20.712152-0400	Cork	Failed while accessing folder: Error Domain=Cork.PackageLoadingError Code=1
default	21:40:20.876133-0400	Cork	Will attempt to place package name
default	21:40:30.910006-0400	Cork	New updates found
default	21:40:30.910305-0400	Cork	Will purge temporary update trackers

**Comment by buresdv** [comment]
Can you please run the command `brew --cellar` in your terminal?

**Comment by 0n0mat0p03ia** [comment]
`/usr/local/Cellar`

Homebrew originally installed on an Intel Mac. Replaced Intel Mac w/ M1 and restored via TimeMachine years ago.

**Comment by buresdv** [comment]
Alright, in that case, can you check if the folder `/opt/homebrew/Cellar` exists on your system?

**Comment by 0n0mat0p03ia** [comment]
> Alright, in that case, can you check if the folder `/opt/homebrew/Cellar` exists on your system?

It doesn't.

**Comment by buresdv** [comment]
Then I'm running out of ideas. The last thing I can think of: Look into `/usr/local/Cellar`. What do you see there?

**Comment by 0n0mat0p03ia** [comment]
I see folders for all my packages in`/usr/local/Cellar`. Symlinks to them are in `/urs/local/bin` and `/usr/local/opt`. Homebrew runs as expected and is up to date. `brew doctor` doesn't report any major issues.

**Comment by buresdv** [comment]
I'm sorry, I really have absolutely no idea why this is happening.

The last resort could perhaps be making a [backup (section Migrate a Homebrew installation to a new location)](https://docs.brew.sh/Tips-N'-Tricks), [uninstalling Homebrew](https://docs.brew.sh/FAQ#how-do-i-uninstall-homebrew) **along with all its folders**, then reinstalling it again and restoring from the backup.

**Comment by 0n0mat0p03ia** [comment]
No worries, thanks for the help. I'll research the backup/delete/restore process. I'm not sure I'll do it or not. For now I can just update Homebrew from the command line as I've done in the past.
