### ISSUE TITLE
Couldn't decipher Homebrew response error

### ISSUE THREAD

**Issue by 0n0mat0p03ia** [buresdv/Cork#385]
### What were you trying to do?

Clicked on `homebrew/core` and `homebrew/cask` taps in UI.

### What was the problem?

"Couldn't decipher Homebrew response error" generated, see screenshot for details. Note: this was raised in #138 but it wasn't the focus of that issue. In #138 the suggestion was to delete homebrew and reinstall it to `/opt/homebrew`, which was performed.

[
![Screenshot 2024-08-18 at 8 24 15 PM](https://github.com/user-attachments/assets/e1097109-16aa-4e87-8e89-f640eb8a0e14)
](url)

### Error logs

```shell
default	20:25:41.662323-0400	Cork	Cached downloads contents: <private>
error	20:25:41.664923-0400	Cork	Could not get proxy host
error	20:25:41.679020-0400	Cork	Couldn't find homebrew/core in local taps
error	20:25:41.679059-0400	Cork	Couldn't find homebrew/cask in local taps
default	20:25:41.944473-0400	Cork	Will attempt to place package name
error	20:25:48.876727-0400	Cork	Failed while decoding tap info: The data couldn’t be read because it is missing.
-Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "formulaFiles", intValue: nil), Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"formulaFiles\", intValue: nil) (\"formulaFiles\").", underlyingError: nil))
error	20:25:48.876854-0400	Cork	Failed while parsing package info: Cork.JSONParsingError.couldNotDecode(failureReason: "The data couldn’t be read because it is missing.")
error	20:25:49.780988-0400	Cork	There was an error decoding the outdated package retrieval output: The data couldn’t be read because it isn’t in the correct format.
Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected end of file" UserInfo={NSDebugDescription=Unexpected end of file})))
error	20:25:49.781111-0400	Cork	Could not decode outdated package command output: <private>
error	20:25:50.622288-0400	Cork	Failed while decoding tap info: The data couldn’t be read because it is missing.
-Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "formulaFiles", intValue: nil), Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"formulaFiles\", intValue: nil) (\"formulaFiles\").", underlyingError: nil))
error	20:25:50.622370-0400	Cork	Failed while parsing package info: Cork.JSONParsingError.couldNotDecode(failureReason: "The data couldn’t be read because it is missing.")
```

### App Version

1.4.4

### App Acquisition

Bought

### Final checklist

- [X] This report is about the interface, and I included screenshots of the problem

**Comment by WladyX** [comment]
i have a similar issue:
![CleanShot 2024-08-19 at 19 29 03@2x](https://github.com/user-attachments/assets/00d95f55-21fd-4b76-aa09-1b8597d3e631)

**Comment by buresdv** [comment]
Try the attached executable
[Cork.zip](https://github.com/user-attachments/files/16663145/Cork.zip)

**Comment by WladyX** [comment]
> Try the attached executable [Cork.zip](https://github.com/user-attachments/files/16663145/Cork.zip)

Works for me, thank you!

**Comment by 0n0mat0p03ia** [comment]
> Try the attached executable [Cork.zip](https://github.com/user-attachments/files/16663145/Cork.zip)

Does not work for me, now generates the same error as reported by @WladyX. Also realized I linked to the wrong issue in my first comment. I first reported this as part of #381 not #138.

![Screenshot 2024-08-20 at 11 42 49 AM](https://github.com/user-attachments/assets/f7debf8d-d27c-47e9-a4b5-798b23930542)

default	11:44:18.975881-0400	Cork	Cached downloads contents: <private>
error	11:44:18.985536-0400	Cork	Could not get proxy host
error	11:44:19.034787-0400	Cork	Couldn't find homebrew/core in local taps
error	11:44:19.034802-0400	Cork	Couldn't find homebrew/cask in local taps
default	11:44:19.298913-0400	Cork	Will attempt to place package name
error	11:44:27.567744-0400	Cork	Failed while decoding tap info: The data couldn’t be read because it is missing.
-Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "formulaFiles", intValue: nil), Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"formulaFiles\", intValue: nil) (\"formulaFiles\").", underlyingError: nil))
error	11:44:27.567892-0400	Cork	Failed while parsing package info: Cork.JSONParsingError.couldNotDecode(failureReason: "The data couldn’t be read because it is missing.")
error	11:44:29.588289-0400	Cork	Failed while decoding tap info: The data couldn’t be read because it is missing.
-Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "formulaFiles", intValue: nil), Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"formulaFiles\", intValue: nil) (\"formulaFiles\").", underlyingError: nil))
error	11:44:29.588362-0400	Cork	Failed while parsing package info: Cork.JSONParsingError.couldNotDecode(failureReason: "The data couldn’t be read because it is missing.")

**Comment by buresdv** [comment]
@0n0mat0p03ia what tap are you trying to see?

**Comment by 0n0mat0p03ia** [comment]
> @0n0mat0p03ia what tap are you trying to see?

homebrew/core and homebrew/cask

**Comment by buresdv** [comment]
What's the output of the command `brew tap-info --json homebrew/cask`? It will probably be very long

**Comment by 0n0mat0p03ia** [comment]
See attached output.
[homebrew_tap_info.txt](https://github.com/user-attachments/files/16737192/homebrew_tap_info.txt)

**Comment by buresdv** [comment]
@0n0mat0p03ia scratch the previous message, you're right. Homebrew changed something in the API again without telling me about it and now a field that was required before is no longer required. I will fix this momentarily

**Comment by buresdv** [comment]
@0n0mat0p03ia This build fixes the issue for me. Can you confirm?

[Cork.zip](https://github.com/user-attachments/files/16821580/Cork.zip)

**Comment by 0n0mat0p03ia** [comment]
Yes this works, no error generated.

**Comment by buresdv** [comment]
Perfect 👍

**Comment by ruslaniv** [comment]
I still have this problem on the latest 1.7.5 licensed version

<img width="897" height="645" alt="Image" src="https://github.com/user-attachments/assets/1cfa6897-9bb9-46c9-929a-3623362b38d7" />

**Comment by buresdv** [comment]
@ruslaniv Can you do `brew --version` in the Terminal?

**Comment by ruslaniv** [comment]
```shell
⇒   brew --version
Homebrew 5.1.13
```

**Comment by buresdv** [comment]
@ruslaniv I couldn't reproduce the issue on the same Homebrew and Cork version, I tried both a [fresh compile](https://github.com/user-attachments/assets/b935d6eb-c95f-400d-8d2e-5a115b8c590f) and the [version available through Homebrew](https://github.com/user-attachments/assets/ef30b97e-bb8a-4426-92b5-a127d6a98875).

Have you made any modifications to your Homebrew, files, or anything else connected to Homebrew?

**Comment by ruslaniv** [comment]
No, I have not made any modifications. 
Right now the app works, it looks like it works most of the time but randomly stops working
Is there an option to save logs so I can send them when it stops working?

**Comment by buresdv** [comment]
@ruslaniv I got one more idea, can you please do `brew info --cask --json=v2 cork` and share the output?

**Comment by ruslaniv** [comment]
> [@ruslaniv](https://github.com/ruslaniv) I got one more idea, can you please do `brew info --cask --json=v2 cork` and share the output?

```json
{
  "formulae": [],
  "casks": [
    {
      "token": "cork",
      "full_token": "cork",
      "old_tokens": [],
      "tap": "homebrew/cask",
      "name": [
        "Cork"
      ],
      "desc": "GUI companion app for Homebrew",
      "homepage": "https://corkmac.app/",
      "url": "https://corkmac.app/RLS/1.7.6/Cork.zip",
      "url_specs": {},
      "version": "1.7.6",
      "autobump": true,
      "no_autobump_message": null,
      "skip_livecheck": false,
      "installed": "1.7.5",
      "installed_time": 1778838059,
      "bundle_version": "113",
      "bundle_short_version": "1.7.5",
      "pinned": false,
      "pinned_version": null,
      "outdated": true,
      "sha256": "5d341b1b6256386961b7366e92e9d3b668c747af52e78658e06a788ea18c695c",
      "artifacts": [
        {
          "app": [
            "Cork.app"
          ],
          "target": "/Applications/Cork.app"
        },
        {
          "zap": [
            {
              "trash": [
                "~/Documents/Cork",
                "~/Library/Caches/com.davidbures.cork",
                "~/Library/HTTPStorages/com.davidbures.cork",
                "~/Library/Preferences/com.davidbures.cork.plist",
                "~/Library/Saved Application State/com.davidbures.cork.savedState"
              ]
            }
          ]
        }
      ],
      "caveats": null,
      "caveats_rosetta": null,
      "depends_on": {
        "macos": {
          ">=": [
            "14"
          ]
        }
      },
      "conflicts_with": null,
      "container": null,
      "rename": [],
      "auto_updates": null,
      "deprecated": false,
      "deprecation_date": null,
      "deprecation_reason": null,
      "deprecation_replacement_formula": null,
      "deprecation_replacement_cask": null,
      "deprecate_args": null,
      "disabled": false,
      "disable_date": null,
      "disable_reason": null,
      "disable_replacement_formula": null,
      "disable_replacement_cask": null,
      "disable_args": null,
      "tap_git_head": "334514a23d6e0ed49fbb3cc1774b48d59388220c",
      "languages": [],
      "ruby_source_path": "Casks/c/cork.rb",
      "ruby_source_checksum": {
        "sha256": "bbc1faa3c0a351124849e074501bea579b90d0585ef2eef8e78f40e522587355"
      }
    }
  ]
}
```
