### ISSUE TITLE
`Package.swift` file is needed for `swift build` and `swift test`

### ISSUE THREAD

**Issue by cclauss** [buresdv/Cork#387]
### Suggestion type

The way Cork works

### What is your idea about?

* #378 runs `swift build` and `swift test` but they currently fail looking for a `Package.swift` file.

This project has [numerous `Package.swift` files](https://github.com/search?q=repo%3Aburesdv%2FCork+Package.swift&type=code) but none at the root of the project.

What is the best way to run `swift build` and `swift test`?  Should we `cd` into each directory and run these commands or is there a way to create a project-wide `Package.swift` that allows the building and testing of all files?

### Why should this be added?

Automated testing helps us find bugs in new code submissions before manual code review.

### Keeping it real

- [X] Adding suggestion idea is realistic

**Comment by buresdv** [comment]
Hey, I don't want to rush you :) Have you had a chance to look at this more?

**Comment by buresdv** [comment]
Closed due to inactivity
