### ISSUE TITLE
Add more possible Brew paths

### ISSUE THREAD

**Issue by buresdv** [buresdv/Cork#39]
In some instances, the path to the brew command might be different, for example when Homebrew is installed through Git instead of their script. See https://elk.zone/glasgow.social/@sandy/109998976036176844

As the brew command is alsu used extensively, it would be a good idea to include it in `AppConstants` instead of having to write it out every time.

Proposed fix:
1. Add the path to the Brew command to `AppConstants`
2. Implement a system for checking which path is correct
3. Add an option to choose the location of Brew in settings, perhaps in the `General` tab

**Comment by jmb** [comment]
FYI... This also applies to these lines in `App Constants.swift`:

```
    static let brewCellarPath: URL = URL(string: "/opt/homebrew/Cellar")!
    static let brewCaskPath: URL = URL(string: "/opt/homebrew/Caskroom")!
```

Hope this helps!

**Comment by buresdv** [comment]
What are these two paths for you? So I know

**Comment by sandydunlop** [comment]
For me they are:

/usr/local/Cellar
/usr/local/Caskroom

**Comment by buresdv** [comment]
@sandydunlop could you test the newest build from branch `[multiple-brew-paths](https://github.com/buresdv/Cork/tree/multiple-brew-paths)`?

@jmb, once @sandydunlop confirms that the fix is working, I will also implement it in your macOS 12 build.

**Comment by jmb** [comment]
Yes, also `/usr/local`

**Comment by sandydunlop** [comment]
I’ll be back at my computer in about 2 hours and will be able to check
then. Had to go outside for a bit.

**Comment by buresdv** [comment]
Of course, no worries!

**Comment by sandydunlop** [comment]
This works for me, sorry for the delay.

Thanks,
Sandy

**Comment by buresdv** [comment]
Amazing, good to hear! I will merge it into main in that case.

@jmb I will update your macOS 12 build to implement this fix and then tell you when it's done

**Comment by buresdv** [comment]
@jmb Here's your macOS 12 version with the fix implemented. I have also implemented fixes for https://github.com/buresdv/Cork/issues/20 and https://github.com/buresdv/Cork/issues/38, which were not a part of your original build, but I wanted to fix them for you :)
[Cork.zip](https://github.com/buresdv/Cork/files/10945692/Cork.zip)

**Comment by buresdv** [comment]
The option for choosing your own paths is not implemented, perhaps in the future. This fix should cover all possible cases, unless the user does something batshit like moving the executable manually and not symlinking it.

**Comment by sandydunlop** [comment]
That sounds like the best way to do this. Totally agree that choosing arbitrary paths wouldn’t be the way to go. 

I can’t imagine there would be any other sensible paths.

Thanks for the quick response on this :-)

**Comment by buresdv** [comment]
No worries, and I thank you for your support :)

**Comment by jmb** [comment]
> @jmb Here's your macOS 12 version with the fix implemented. I have also implemented fixes for #20 and #38, which were not a part of your original build, but I wanted to fix them for you :)
> [Cork.zip](https://github.com/buresdv/Cork/files/10945692/Cork.zip)

Thank you this is amazing!

**Comment by buresdv** [comment]
Hey guys, could you please run `brew tap-info homebrew/core` and send me the output? I'm working on faster loading of Taps and I need to know where they are located for you, so this new system works for you
@jmb @sandydunlop

**Comment by jmb** [comment]
Here you go:

```
$ brew tap-info homebrew/core                                                                         ✔  16:10:31 
homebrew/core: 3 commands, 6540 formulae
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (6,995 files, 557.5MB)
From: https://github.com/Homebrew/homebrew-core
```

**Comment by buresdv** [comment]
@jmb could you test this build if all the tap features work? 
[Cork_LD.zip](https://github.com/buresdv/Cork/files/11008628/Cork_LD.zip)

@sandydunlop can you test this build, again if the taps load and the 
[Cork.zip](https://github.com/buresdv/Cork/files/11008639/Cork.zip)
adding/removing of taps works?

**Comment by jmb** [comment]
It's running ok, but I'm unsure what I need to test. If I right-click a tap in the left menu and choose "Remove", nothing happens.

When I click Update on the main screen to update my outdated packages, it says it's pulling updates, but also doesn't seem to do anything - the list remains.

**Comment by buresdv** [comment]
@jmb could you try running the branch `lower-deployment-target` from Xcode and seeing what errors it gives?

**Comment by jmb** [comment]
> @jmb could you try running the branch `lower-deployment-target` from Xcode and seeing what errors it gives?

No major issues, the only minor error is `[SwiftUI] No symbol named 'spigot' found in system symbol set`.
👍🏻

**Comment by jmb** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/110238/226347833-4e4aa0c0-5005-43a6-b4a1-82ccd0678ed2.png">

**Comment by buresdv** [comment]
I will try to fix that missing icon 😅 Apart from the icon, everything else works? Namely the problem with the taps and updating

**Comment by buresdv** [comment]
Here it is, I hope it will work:


[Cork.zip](https://github.com/buresdv/Cork/files/11020232/Cork.zip)
