### ISSUE TITLE
Add keyboard shortcuts for searching

### ISSUE THREAD

**Issue by yerbestpal** [buresdv/Cork#40]
Something like cmd+f to highlight the search field in the sidebar to search for installed packages. It feels natural to use cmd+f and expect a search field to be highlighted, especially in native apps.

**Comment by buresdv** [comment]
I tried implementing this multiple times before, but I could never manage it. I'm using .searchable as the search field, and Apple doesn't allow adding keyboard shortcuts to it.

I will definitely keep this in mind and see if I can eventually come up with a solution.

**Comment by yerbestpal** [comment]
https://stackoverflow.com/a/71930128/8303752 Might this work?

**Comment by buresdv** [comment]
It was one of my first guesses, but this approach doesn't work because the search field is not in the toolbar, but in the sidebar. I don't know how hard it would be to adapt it, but I will have a look at it right after I resolve https://github.com/buresdv/Cork/issues/39

**Comment by buresdv** [comment]
Not possible at the moment, pausing for now

**Comment by buresdv** [comment]
Implemented for macOS 14+
