### ISSUE TITLE
Not Agreed to Xcode License

### ISSUE THREAD

**Issue by SteveMattan** [buresdv/Cork#406]
### What were you trying to do?

1. Run Cork to check for updates to installed software.
2. Clicking on an Installed Formula

### What was the problem?

1. I get the following message: "Couldn't check for outdated packages Unimplemented error for getting outdated packages: Error: You have not agreed to the Xcode license. Please resolve this by running: sudo xcodebuiild -license accept"

2. I get the same message as for 1, pre-pended with: "Invalid Homebrew Response Homefrew returned JSON with the following error: ..."

macOS 14.6.1

### Error logs

```shell
For 1. 
default	07:35:23.226299-0400	Cork	Ignorable update function error: Error:

For 2.
error	07:44:55.197125-0400	Cork	Standard error of the package details loading function is not empty. Will investigate if the error can be ignored.
error	07:44:55.197220-0400	Cork	Error was serious enough to throw an error
error	07:44:55.197290-0400	Cork	Failed while parsing package info: Cork.BrewPackageInfoLoadingError.standardErrorNotEmpty(presentError: "Error: You have not agreed to the Xcode license. Please resolve this by running:\n  sudo xcodebuild -license accept\n")
```

### App Version

1.4.5 (78)

### App Acquisition

Bought

### Final checklist

- [ ] This report is about the interface, and I included screenshots of the problem

**Comment by buresdv** [comment]
You have to run `sudo xcodebuiild -license accept` in Terminal

**Comment by SteveMattan** [comment]
Yes, that is obvious, but why. What changed to require this? Thanks.

**Comment by buresdv** [comment]
Nothing in Cork, but I believe that an update to Xcode's tooling sometimes requires you to accept the licensing again

**Comment by SteveMattan** [comment]
Thanks again. It is working now, although I had to restart Cork twice before it recognized the change, which was what was confusing me.

**Comment by buresdv** [comment]
No problem, I'm happy to hear it works well now
