### ISSUE TITLE
Xcode version 16.0, incompatible with project's Xcode version requirement

### ISSUE THREAD

**Issue by TickDracy** [buresdv/Cork#407]
Hello, I'm trying to compile the latest version on macOS 14.7, with the latest Xcode 16, but I'm getting an error when running the following command: `git clone https://github.com/buresdv/Cork.git && cd Cork && mise use tuist@4.25.0 && tuist install && tuist generate --no-binary-cache`.

The error I'm getting is:
![SCR-20240918-csbp](https://github.com/user-attachments/assets/23ee7413-f112-437e-8485-e861f2955d27)

```
The selected Xcode version is 16.0, which is not compatible with this project's Xcode version requirement of 15.0.0..<16.0.0.
Fatal linting issues found
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

Could you please advise on this?

Best regards!

**Comment by buresdv** [comment]
Yes, use the Xcode version supported by the project, which is 15.4. Use [Xcodes](https://www.xcodes.app) to download the right version

**Comment by TickDracy** [comment]
> Yes, use the Xcode version supported by the project, which is 15.4. Use [Xcodes](https://www.xcodes.app) to download the right version

Thanks a lot. I was not aware of **Xcodes**.

**Comment by azlkiniue** [comment]
![image](https://github.com/user-attachments/assets/e4be0f55-9419-4836-ba1a-dcc858412b19)

Hello @buresdv, I just managed to compile it using Xcode 16, does it means that the Tuist config can be updated? Sorry for a noob question.

**Comment by buresdv** [comment]
@azlkiniue No problem, I'm doing the transition right now and it might work now. I'm not sure, I'm still not done with it
