### ISSUE TITLE
Menu Bar Bug: No Icon in macOS 15.0 

### ISSUE THREAD

**Issue by Luca1991** [buresdv/Cork#408]
### What were you trying to do?

I wanted Cork to be shown in menu bar and launched without its main window.

### What was the problem?

I enabled from Settings menu:
1) "Show in Menu Bar"
2) "Open Cork without its main window"

Now when I start Cork I no longer see the main window, nor the icon in the menu bar.

IMPORTANT NOTE: If I only enable "Show in menu bar", the menu bar icon displays correctly.

### Error logs

```shell
Is this even needed for this bug report?
```

### App Version

1.4.5

### App Acquisition

Bought

### Final checklist

- [ ] This report is about the interface, and I included screenshots of the problem

**Comment by buresdv** [comment]
Thanks for the report, I'll look into it. It might just take a while, because I'm still transitioning the rest of the codebase to the new conventions introduced in macOS 15. Couldn't test them in advance because I only have one Mac, and it's my only work machine!

**Comment by megabubbletea** [comment]
Thanks @Luca1991 and @buresdv. Con confirm I have the same issue after upgrading to macOS 15 been bugging me a couple days now and thought it was just me since no-one had reported it yet. 😂

**Comment by Thisisauser6443** [comment]
I've also got the same issue, but the kicker here is that I'm still on Sonoma

**Comment by bigtreiber** [comment]
Same issue here since 3 weeks ... Cork is unusable :-(
Any chance this issue will be addressed in the near future?

**Comment by buresdv** [comment]
I looked into it and this is definitely an Apple bug. As you can see here, the icon is actually there, but it's invisible:
![Snímek obrazovky 2024-10-12 v 12 04 59](https://github.com/user-attachments/assets/4b7b001c-6287-4e07-82bb-105523bdf425)

The problem is here:
```swift
func applicationWillFinishLaunching(_: Notification)
{
    if startWithoutWindow
    {
        NSApp.setActivationPolicy(.accessory) <-- here
    }
    else
    {
        NSApp.setActivationPolicy(.regular)
    }
}
```

Setting the activation policy to `.accessory` is what breaks the entire process. I have not changed anything in this code ever the feature came out almost a year ago, so this is something that Apple did.

I implemented a fix that removes the option to start the app without the main window, which also fixes this issue until Apple fixes it on their end.

**Comment by Luca1991** [comment]
Hi @buresdv 
Thanks a lot for the workaround, I hope Apple fixes this bug soon.
Should I close this issue now?

**Comment by buresdv** [comment]
No problem @Luca1991, thank you for your patience. I will close the issue 😊

**Comment by buresdv** [comment]
The release of the hotfix got a bit delayed because I might have discovered another thing Apple broke - I'm waiting for testers to get back to me

**Comment by buresdv** [comment]
Implemented in release `1.4.6`

**Comment by megabubbletea** [comment]
Nice. Good to see the Cork icon back I noted menu bar!

**Comment by texastoland** [comment]
Continued from https://github.com/buresdv/Cork/issues/637#issuecomment-4745561416:

I found the following workaround from a link in this thread and a few other sources:

```swift
    func applicationWillFinishLaunching(_ notification: Notification) {
        // Workaround for issue [#147](https://github.com/jacklandrin/OnlySwitch/issues/147)
        NSApp.setActivationPolicy(.accessory)
    }
```

Does it persist if you defer activation?

**Comment by texastoland** [comment]
Do I need to do anything special to repro if I build locally?
