### ISSUE TITLE
Claims package corruption on every open

### ISSUE THREAD

**Issue by aidan-gibson** [buresdv/Cork#410]
### What were you trying to do?

Open Cork.

### What was the problem?

<img width="266" alt="image" src="https://github.com/user-attachments/assets/0f6196a1-0b75-455b-a044-391fd3a28b2d">

I've "repaired" it countless times, tried reinstalling, etc etc.

I think the issue is, the package is called autodesk-fusion, but if you look at the [homebrew page](https://formulae.brew.sh/cask/autodesk-fusion#default), it was formerly called autodesk-fusion360. I believe what's tripping it up is this "Former tokens" part of homebrew.

### Error logs

```shell
default	01:16:05.090631-0700	Cork	Cached downloads contents: <private>
error	01:16:05.163877-0700	Cork	Package URL file:///opt/homebrew/Caskroom/autodesk-fusion360/ has no versions installed
error	01:16:05.165786-0700	Cork	Failed while getting package version for package <private>. Package does not have any version installed.
error	01:16:05.173460-0700	Cork	Package URL file:///opt/homebrew/Caskroom/autodesk-fusion/ has no versions installed
error	01:16:05.174114-0700	Cork	Failed while getting package version for package <private>. Package does not have any version installed.
error	01:16:05.328041-0700	Cork	Could not get proxy host
error	01:16:06.227976-0700	Cork	Failed while accessing folder: Error Domain=Cork.PackageLoadingError Code=2
default	01:16:09.286174-0700	Cork	Will attempt to place package name
```

### App Version

1.4.5

### App Acquisition

Self-Compiled

### Final checklist

- [ ] This report is about the interface, and I included screenshots of the problem

**Comment by buresdv** [comment]
Yeah, I think you're right with the former name. That should be the problem.

**Comment by aidan-gibson** [comment]
Any chance the fix would be trivial? It kinda completely prevents me from using Cork. Also, bizarrely, when I just opened it, it shows: `Repair fwupd` as the option instead (`fwupd` is other brew software I have)
<img width="261" alt="image" src="https://github.com/user-attachments/assets/30bd6aec-f474-4d68-bb6a-c75c8aa5a79f">

**Comment by buresdv** [comment]
@aidan-gibson It's pretty difficult to pinpoint/fix the problem. Internally, this error appears when there's an empty folder in the folder that holds the packages. It doesn't care about the Homebrew package database, since the loading happens completely separately.

If you want to try fixing this manually, I'd recommend you look for `autodesk-fusion360` and `fwupd` in either the Cellar or Cask folder (I'm not sure if these are Formulae or Casks). So either `/opt/homebrew/Cellar` or `/opt/homebrew/Caskroom`. See which of these packages has the empty folder, and then delete it.

**Comment by aidan-gibson** [comment]
Good enough for me! Had to delete `autodesk-fusion360` from Caskroom and `fwupd` from Cellar, works fine now, thanks!
