### ISSUE TITLE
Maybe it's better to generate a token?

### ISSUE THREAD

**Issue by yurii-shcherbiuk** [buresdv/Cork#413]
### Suggestion type

The way Cork works

### What is your idea about?

Perhaps it’s better to generate a token on the server based on the user’s email and send it to clients when they make a purchase, and even create a website that sends the token  to email upon request (in case the message is lost)? :D

![ops](https://github.com/user-attachments/assets/4a67f49d-284d-49c0-8f80-8770527ea78f)

### Why should this be added?

-

### Keeping it real

- [X] Adding suggestion idea is realistic

**Comment by buresdv** [comment]
My email was enabled only temporarily for internal testing purposes - good on you for stumbling upon it, but this will no longer work :)

**Comment by yurii-shcherbiuk** [comment]
> My email was enabled only temporarily for internal testing purposes - good on you for stumbling upon it, but this will no longer work :)

Hmm, for instance, a contributor’s email, like @utkinn, could also serve as a free activation (just like any other email that has been exposed). It would be better to switch the system to tokens instead :D
