### ISSUE TITLE
It would be great to create a merge with brew client Applite

### ISSUE THREAD

**Issue by giovariot** [buresdv/Cork#416]
### Suggestion type

Both

### What is your idea about?

I think the way more advanced way Cork works compared to products such as [milanvarady/Applite](https://github.com/milanvarady/Applite) is amazing. Still I think the clean and easy to use approach of Applite could be helpful to create a more appealing and complete program to manage brew even for non power users.

### Why should this be added?

This should enable a more straightforward usage of casks for users that are using brew only to manage and keep their apps updated while also allowing more advanced users to manage more obscure packages and dependencies.

### Keeping it real

- [X] Adding suggestion idea is realistic

**Comment by buresdv** [comment]
This is not realistic, or feasible. Thank you for the idea though.
