### ISSUE TITLE
I thought I paid for Cork...?

### ISSUE THREAD

**Issue by mapleroyal** [buresdv/Cork#418]
### What were you trying to do?

Use Cork

### What was the problem?

I think there used to be an option where donating to you via github would give us access to the full app.

I had the full app for a long time, but I recently had to wipe my mac and start over. Now when I install and run cork, it asks the email I bought it with. But I didn't buy it with an email, I got it through donating in github (I think that was the process).

Sorry if this is the wrong place, I couldn't find an email to contact you. Also, that was quite awhile ago so I may be misremembering the process.

### Error logs

```shell
n/a
```

### App Version

1.4.5.2 (81)

### App Acquisition

Bought

### Final checklist

- [X] This report is about the interface, and I included screenshots of the problem

**Comment by buresdv** [comment]
That used to be the old way to get the app, but it hasn't been the case for some time. Check out the relevant part of the README:

https://github.com/buresdv/Cork?tab=readme-ov-file#getting-cork

Specifically:
> Buy Cork for 25€ through the [website](https://corkmac.app/).

Now you have to buy it through the website.

If you send me an email with your GitHub receipt do `dev@corkmac.app`, I'll add your email and it will work.

**Comment by mapleroyal** [comment]
Sent. Thanks!

**Comment by buresdv** [comment]
Sweet, I added you :)
