### ISSUE TITLE
Command not found: tuist

### ISSUE THREAD

**Issue by tsuliwaensis** [buresdv/Cork#424]
### What were you trying to do?

Trying to compile Cork, and I have both mise and tuist installed but when I try to clone the repo, it returns `zsh: command not found: tuist`. Checking `mise list` returns `tuist 4.25.0`. I've tried uninstalling tuist and reinstalling it with mise but that did not solve the issue. 

### What was the problem?

Can't compile

### Error logs

```shell
`
git clone https://github.com/buresdv/Cork.git && cd Cork && mise use tuist@4.25.0 && tuist install && tuist generate --no-binary-cache
Cloning into 'Cork'...
remote: Enumerating objects: 12782, done.
remote: Counting objects: 100% (3068/3068), done.
remote: Compressing objects: 100% (1064/1064), done.
remote: Total 12782 (delta 2155), reused 2657 (delta 1963), pack-reused 9714 (from 1)
Receiving objects: 100% (12782/12782), 11.07 MiB | 37.04 MiB/s, done.
Resolving deltas: 100% (7868/7868), done.
mise ~/Cork/.mise.toml tools: tuist@4.25.0
zsh: command not found: tuist
````
```


### App Version

1.4.5

### App Acquisition

Self-Compiled

### Final checklist

- [ ] This report is about the interface, and I included screenshots of the problem

**Comment by tsuliwaensis** [comment]
I reinstalled tuist with homebrew and that fixed the issue

**Comment by buresdv** [comment]
@tsuliwaensis I reverted the install instructions for Tuist in the readme. Try going through it again. Installing Tuist through Homebrew is not recommended and it will break once I change the version required by Cork

**Comment by Michael-Z-Freeman** [comment]
Had this problem a well. Using Homebrew install fixed it as well.
