### ISSUE TITLE
Add support for choosing a language under Settings

### ISSUE THREAD

**Issue by eltercero** [buresdv/Cork#431]
### Suggestion type

The way Cork works

### What is your idea about?

By default, Cork uses the language (English, Spanish, etc.) you have in macOS and it can't be changed. I suggest adding a new setting (maybe in General tab) to allow changing the language of the app. It can be a dropdown with the available languages. 

### Why should this be added?

As for my particular case, even though English is not my native language, I'd rather have all my dev apps in that language. 

### Keeping it real

- [X] Adding suggestion idea is realistic

**Comment by nc-z** [comment]
This is already a macOS feature; you can change the language of any application individually in Settings. This would just be wasted development time IMO.

**Comment by eltercero** [comment]
> This is already a macOS feature; you can change the language of any application individually in Settings. This would just be wasted development time IMO.

I didn't know this. Thanks a lot! I'll close the issue.
