### ISSUE TITLE
Collapsible sidebar sections

### ISSUE THREAD

**Issue by infotexture** [buresdv/Cork#79]
With a long list of installed packages, it's hard to find things in the sidebar, as it shows everything by default.

In addition to the shorter labels proposed in #77 ~~and the sorting suggestion from #78,~~ it might help to make the section titles collapsible like in the Finder sidebar, so you can expand/collapse sections to focus on **Formulae**, **Casks**, **Taps**, or whatever you're interested in seeing.

![Finder_collapsible-sidebar-sections](https://user-images.githubusercontent.com/129995/228239375-98b51de7-8bfd-40f1-a39b-453335ac6293.gif)

**Comment by buresdv** [comment]
Collapsible sections were implemented at one point, but they were causing visual glitches due to a SwiftUI bug (#27). Until Apple fixes the SwiftUI bug, the sections can't be made collapsible
